students_name = str (input("Students's name: "))
eng = int (input("Grade in English: "))
fil = int (input("Grade in Filipino: "))
sci = int (input("Grade in Science: "))
math = int (input("Grade in Math: "))
ap = int (input("Grade in Araling Panlipunan: "))
pe = int (input("Grade in Physical Education: "))
ave = (eng + fil + sci + math + ap + pe) / (6)

print ("Student's name: " + students_name)
print ("STUDENT'S GRADES")
print ("English: " , eng)
print ("Filipino: " , fil)
print ("Science: " , sci)
print ("Math: " , math)
print ("Araling Panlipunan: " , ap)
print ("Physical Education: " , pe)
print ("Average: " , ave)